name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing GitHub Actions

on:

  push:

  workflow_dispatch:

jobs:

  Explore-GitHub-Actions:

    runs-on: self-hosted

    steps:

      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

    
